#!/bin/bash
#
#  Change-colors for Flattr Icons theme.
#
#  Copyright 2014 fenexomega <github.com/fenexomega>
#  
#  Usage: change-colors [color]
#  Colors: default black blue brown cyan green grey darkred orange red violet yellow 
#
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

auxtxt='/tmp/aux.txt'
tmpsvg='/tmp/tmp.svg'

#List of Color Hex
default='1abc9c'
black='2c3e50'
blue='3498db'
brown='d35400'
cyan='00d9ff'
green='27ae60'
grey='bdc3c7'
darkred='c0392b'
orange='e67e22'
red='e74c3c'
violet='9b59b6'
yellow='f1c40f'


showHelp(){
	echo Usage: change-colors [color]
	echo -e "Colors: default black blue brown cyan green grey darkred orange red violet yellow \n"
	echo -e "e.g.:\n change-colors red\n"
}


if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
	showHelp
	exit 0
fi

#If user have gdialog, use it
if [ -f /usr/bin/gdialog ]; then
dialog='gdialog'
else
dialog='dialog'
fi

if [ "$1" == "" ]; then
	$dialog --menu "Choose your folders color" 20 40 10 default '1abc9c' black '2c3e50' blue '3498db' brown 'd35400' cyan '00d9ff' green '27ae60' grey 'bdc3c7' darkred 'c0392b' orange 'e67e22' red 'e74c3c' violet '9b59b6' yellow 'f1c40f' 2> $auxtxt
	test "$?" != "0" && exit 1
	
	Color=$(cat $auxtxt)
	Color=${!Color}
	
else
	Color=${!1}
	if [ "$Color" == "" ]; then
		echo "Error: Invalid Color."
		showHelp
		exit 1
	fi
fi


inputfolder="places-folders/scalable"
auxfolder="/tmp/new_folders"
outputfolder="places/scalable"

cd $inputfolder/
mkdir $auxfolder/
for file in * ; do 
	if [[ $file == *.svg* ]] && [ $file != "$tmpsvg" ] ; then
	sed -e "s/$default/$Color/" $file > $tmpsvg
	cat $tmpsvg > "$auxfolder/$file" 
	fi
done
rm $tmpsvg 
cp $auxfolder/* ../../"places/scalable"
rm -r $auxfolder


#Change and copy the small images
inputfolder="places-folders/small"
outputfolder="places/scalable"

cd ../../
cd $inputfolder/
mkdir $auxfolder/
for file in * ; do 
	if [[ $file == *.svg* ]] && [ $file != "$tmpsvg" ] ; then
	sed -e "s/$default/$Color/" $file > $tmpsvg
	cat $tmpsvg > "$auxfolder/$file" 
	fi
done
rm $tmpsvg 
cp $auxfolder/* ../../"places/small"
rm -r $auxfolder

exit 0
